import BussinessClientSlider from "@/components/common/BussinessClient";
import Footer from "@/components/common/Footer";
import SmoothScroll from "@/components/common/SmoothScroll";
import BlogGrid from "@/components/pages/home/BlogGrid";
import CarsoulSlider from "@/components/pages/home/CarsoulSlider";
import CoreFeatures from "@/components/pages/home/CoreFeatures";
import Hero from "@/components/pages/home/Hero";
import KnowMore from "@/components/pages/home/KnowMore";
import OfficeDetailGrid from "@/components/pages/home/OfficeDetailGrid";
import Review from "@/components/pages/home/Review";
import { slides } from "@/utils/constant";
import useTranslation from "next-translate/useTranslation";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
    const { t } = useTranslation();
    const router = useRouter();
    const { pathname, query } = router;
    return (
        <SmoothScroll>
            <Head>
                <title>Codecony</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <meta
                    property="og:title"
                    content="Codecony description"
                />
                <meta
                    property="og:description"
                    content="Offering tour packages for individuals or groups."
                />
                <meta
                    property="og:image"
                    content="http://euro-travel-example.com/thumbnail.jpg"
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero />
            <CoreFeatures />
            <OfficeDetailGrid />
            <KnowMore />
            <Link
                locale={"fr"}
                href={{ pathname, query }}
                // as={asPath}
            >
                <span> (FR)</span>
                Change to fr
            </Link>
            <Link
                locale={"en"}
                href={{ pathname, query }}
                // as={asPath}
            >
                <span> (en)</span>
                Change to en
            </Link>
            <p>{t("home:variable-example", { count: 42 })}</p>
            <CarsoulSlider slides={slides} />
            <Review />
            <BussinessClientSlider />
            <BlogGrid />
            <Footer />
        </SmoothScroll>
    );
}
